### ISSUE TITLE
Why gs() outputs overflow: hidden?

### ISSUE THREAD

**Issue by zhe** [leny/kouto-swiss#54]
Hi everybody,

Glad to find this great framework for Stylus!

`gs()` outputs `overflow: hidden;` that will hide the elements outside the grid system, what if I want to put an element outside using `margin-left: -40px` for example.

Is there any other reason to output `overflow: hidden`?

Thanks.

**Comment by leny** [comment]
I'm sorry for the (very, _very_) long delay. 
The grid system of Kouto Swiss isn't as good as the **jeet** grid system, this is why I will mark it as _deprecated_, as I see that in nearly all use cases, users use kouto swiss with jeet.
