### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by iho** [leny/kouto-swiss#55]
Potentially unhandled rejection [2] ParseError: /home/ihor/relax/node_modules/kouto-swiss/lib/kouto-swiss.js:11:104
    7| 
    8| var stylus = require( "stylus" ),
    9|     path = require( "path" ),
   10|     nodes = stylus.nodes,
   11|     utils = stylus.utils;
--------------------------------------------------------------------------------------------------------------^
   12| 
   13| exports = module.exports = function() {
   14|     return function( oStyle ){

expected "indent", got ";"

**Comment by leny** [comment]
I'm sorry for the long, _very_ long delay, but... I've never be able to reproduce the error after some tests. I will close this issue, don't hesitate to reopen if you have more information.
