### ISSUE TITLE
+placeholder() - Error: unknown word

### ISSUE THREAD

**Issue by leobaiano** [leny/kouto-swiss#58]
I tried to use the mixin `+placeholder()` as described in the [documentation](http://kouto-swiss.io/docs.html#placeholder), but I received the error unknown word as you can see in the image below.

**Comment by leny** [comment]
Hi, thanks for the report.

Can you provide me more informations, like if Kouto is the only lib you use, what you are using to compile the file, and the complete file so I can make tests on my own?

Thanks.
