### ISSUE TITLE
Px to Rem/Em conversions not processed when stored in a variable

### ISSUE THREAD

**Issue by marpala** [leny/kouto-swiss#60]
Hi, I'm new to both Stylus and Kouto Swiss. I'm trying to convert some pixel values to rem/em using the respective functions in KS. The problem is, they don't seem to be processed when they're stored in a variable. Example:

```
$font-size--big = rem(36px)

h1
  font-size: $font-size--big
```

yields to

```
h1 {
  font-size: rem(36px);
}
```

instead of

```
h1 {
  font-size: 2.25rem;
}
```

**Comment by leny** [comment]
Hi, I'm sorry for the long, _very_ long delay.

I will make some tests and try to fix this. I'm not sure that the bug is related to KoutoSwiss or directly to Stylus. Will dig around.

**Comment by leny** [comment]
After running some tests, I can't reproduce the issue. Was probably a bug from Stylus, fixed since.
Sorry again for the long delay.
