### ISSUE TITLE
Add a bit of documentation for gulp ?

### ISSUE THREAD

**Issue by EmmanuelBeziat** [leny/kouto-swiss#61]
Hi,

> To use **kouto swiss** wioth gulp, use gulp-stylus and include kouto swiss in your `use` option for the task.

I think this lacks an example. I didn't have a clue how to use the `use` option (it's not ont this page https://github.com/stevelacy/gulp-stylus), and i had to find out in a nub issue : https://github.com/stevelacy/gulp-stylus/issues/47

Howerver, what I tried using this example didn't work, so i'm still stuck with importing the file in my stylus project.

Thanks. :)

**Comment by leny** [comment]
Hi,

I put this here for you, and will update docs when I got some time :

```javascript
var gulp = require( "gulp" ),
    koutoSwiss = require( "kouto-swiss" ),
    stylus = require( "gulp-stylus" );

gulp.task( "styles-main", function() {
        gulp.src( "stylus/styles.styl" )
            .pipe( stylus( { 
                "use": koutoSwiss() 
            } ) )
            .pipe( gulp.dest( "css" ) );
    } );
```

**Comment by EmmanuelBeziat** [comment]
I can update the docs with your present example in a pull request if you want.

**Comment by leny** [comment]
Be my guest :)

**Comment by leny** [comment]
Woke up too early (sadly), got some time to made it.
