### ISSUE TITLE
rem()/em() don't compute when called with "use" (gulp)

### ISSUE THREAD

**Issue by EmmanuelBeziat** [leny/kouto-swiss#62]
Hi, 

Now that I have the ability (thanks to you @leny) to use the `use` option in gulp, i used it in my gulpfiles and removed the `@import` i had in my stylus files.

But it sims both rem/em functions aren't processed anymore. If I put back  `@import`, it's immediately ok.

Am I missing something ?

**Comment by leny** [comment]
If you remove the `@import` directive, **kouto-swiss** isn't implemented in your stylesheets.

The `use` option of Stylus is just a way to tell Stylus to link with libs, you still need to include them in the `.styl` files.
