### ISSUE TITLE
"ks-vendors-prefixes = false" kill "align-items" property

### ISSUE THREAD

**Issue by pokkur** [leny/kouto-swiss#64]
When if I set that in a .styl file, then compiled .css file lost the align-items property.

```
ks-vendors-prefixes = false
```
bug?

**Comment by leny** [comment]
Sorry for the delay. 
Probably a bug.
I make some tests and keep you in touch.

**Comment by pokkur** [comment]
@leny Thank you so match✌️

**Comment by leny** [comment]
(don't know why I closed it. I've found the bug, working on a fix)

**Comment by leny** [comment]
Fixed and published as `0.13.1`.

Sorry again for the long delay.

**Comment by pokkur** [comment]
I'm so Happyyyyy 😝
@leny You’re the best!
