### ISSUE TITLE
Docs site is down

### ISSUE THREAD

**Issue by xxxKOTxxx** [leny/kouto-swiss#69]
https://downforeveryoneorjustme.com/kouto-swiss.io

Can You fix it, please?

**Comment by leny** [comment]
Yeah, domain name is expired. Cost me too much for a project like this.

You can get the doc here: http://leny.me/kouto-swiss/ - ~~styles are broken, will try to fix that when I can~~.

**Comment by xxxKOTxxx** [comment]
> Yeah, domain name is expired. Cost me too much for a project like this.
> 
> You can get the doc here: http://leny.me/kouto-swiss/ - ~styles are broken, will try to fix that when I can~.

Thanks You for fast reply, link & great library!

Can You update link on docs in npm & so on?

**Comment by leny** [comment]
I will. I don't have time today, but I will.
